version: "2.4"

services:
  server:
    build:
      context: .
      args:
        - MC_VERSION=26.1
        - EULA=true
        - JAVA_ARGS=-Xms2G -Xmx2G -XX:+UseG1GC
    container_name: mc-server
    restart: unless-stopped
    ports:
      - 25565:25565/tcp # Main port, access the game server
    volumes:
      - ./data:/app/runner/data
